/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Failed to create address
 */
export type AddressesCreateResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Failed to create address
 */
export class AddressesCreateResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: AddressesCreateResponseBodyData;

  constructor(err: AddressesCreateResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AddressesCreateResponseBody";
  }
}

/** @internal */
export const AddressesCreateResponseBody$inboundSchema: z.ZodType<
  AddressesCreateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new AddressesCreateResponseBody(v);
  });

/** @internal */
export type AddressesCreateResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const AddressesCreateResponseBody$outboundSchema: z.ZodType<
  AddressesCreateResponseBody$Outbound,
  z.ZodTypeDef,
  AddressesCreateResponseBody
> = z.instanceof(AddressesCreateResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesCreateResponseBody$ {
  /** @deprecated use `AddressesCreateResponseBody$inboundSchema` instead. */
  export const inboundSchema = AddressesCreateResponseBody$inboundSchema;
  /** @deprecated use `AddressesCreateResponseBody$outboundSchema` instead. */
  export const outboundSchema = AddressesCreateResponseBody$outboundSchema;
  /** @deprecated use `AddressesCreateResponseBody$Outbound` instead. */
  export type Outbound = AddressesCreateResponseBody$Outbound;
}
