/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Discount not found
 */
export type DiscountGetDiscountResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Discount not found
 */
export class DiscountGetDiscountResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DiscountGetDiscountResponseBodyData;

  constructor(err: DiscountGetDiscountResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "DiscountGetDiscountResponseBody";
  }
}

/** @internal */
export const DiscountGetDiscountResponseBody$inboundSchema: z.ZodType<
  DiscountGetDiscountResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new DiscountGetDiscountResponseBody(v);
  });

/** @internal */
export type DiscountGetDiscountResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const DiscountGetDiscountResponseBody$outboundSchema: z.ZodType<
  DiscountGetDiscountResponseBody$Outbound,
  z.ZodTypeDef,
  DiscountGetDiscountResponseBody
> = z.instanceof(DiscountGetDiscountResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountGetDiscountResponseBody$ {
  /** @deprecated use `DiscountGetDiscountResponseBody$inboundSchema` instead. */
  export const inboundSchema = DiscountGetDiscountResponseBody$inboundSchema;
  /** @deprecated use `DiscountGetDiscountResponseBody$outboundSchema` instead. */
  export const outboundSchema = DiscountGetDiscountResponseBody$outboundSchema;
  /** @deprecated use `DiscountGetDiscountResponseBody$Outbound` instead. */
  export type Outbound = DiscountGetDiscountResponseBody$Outbound;
}
