/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Discount not found
 */
export type DiscountUpdateResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Discount not found
 */
export class DiscountUpdateResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DiscountUpdateResponseBodyData;

  constructor(err: DiscountUpdateResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "DiscountUpdateResponseBody";
  }
}

/** @internal */
export const DiscountUpdateResponseBody$inboundSchema: z.ZodType<
  DiscountUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new DiscountUpdateResponseBody(v);
  });

/** @internal */
export type DiscountUpdateResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const DiscountUpdateResponseBody$outboundSchema: z.ZodType<
  DiscountUpdateResponseBody$Outbound,
  z.ZodTypeDef,
  DiscountUpdateResponseBody
> = z.instanceof(DiscountUpdateResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountUpdateResponseBody$ {
  /** @deprecated use `DiscountUpdateResponseBody$inboundSchema` instead. */
  export const inboundSchema = DiscountUpdateResponseBody$inboundSchema;
  /** @deprecated use `DiscountUpdateResponseBody$outboundSchema` instead. */
  export const outboundSchema = DiscountUpdateResponseBody$outboundSchema;
  /** @deprecated use `DiscountUpdateResponseBody$Outbound` instead. */
  export type Outbound = DiscountUpdateResponseBody$Outbound;
}
