/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Price not found
 */
export type PricesGetPriceResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Price not found
 */
export class PricesGetPriceResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PricesGetPriceResponseBodyData;

  constructor(err: PricesGetPriceResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "PricesGetPriceResponseBody";
  }
}

/** @internal */
export const PricesGetPriceResponseBody$inboundSchema: z.ZodType<
  PricesGetPriceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new PricesGetPriceResponseBody(v);
  });

/** @internal */
export type PricesGetPriceResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const PricesGetPriceResponseBody$outboundSchema: z.ZodType<
  PricesGetPriceResponseBody$Outbound,
  z.ZodTypeDef,
  PricesGetPriceResponseBody
> = z.instanceof(PricesGetPriceResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PricesGetPriceResponseBody$ {
  /** @deprecated use `PricesGetPriceResponseBody$inboundSchema` instead. */
  export const inboundSchema = PricesGetPriceResponseBody$inboundSchema;
  /** @deprecated use `PricesGetPriceResponseBody$outboundSchema` instead. */
  export const outboundSchema = PricesGetPriceResponseBody$outboundSchema;
  /** @deprecated use `PricesGetPriceResponseBody$Outbound` instead. */
  export type Outbound = PricesGetPriceResponseBody$Outbound;
}
