/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Subscription not found
 */
export type SubscriptionUpdateSubscriptionSubscriptionsResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Subscription not found
 */
export class SubscriptionUpdateSubscriptionSubscriptionsResponseBody
  extends Error
{
  error: string;

  /** The original data that was passed to this error instance. */
  data$: SubscriptionUpdateSubscriptionSubscriptionsResponseBodyData;

  constructor(
    err: SubscriptionUpdateSubscriptionSubscriptionsResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "SubscriptionUpdateSubscriptionSubscriptionsResponseBody";
  }
}

/**
 * Bad Request
 */
export type SubscriptionUpdateSubscriptionResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Bad Request
 */
export class SubscriptionUpdateSubscriptionResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: SubscriptionUpdateSubscriptionResponseBodyData;

  constructor(err: SubscriptionUpdateSubscriptionResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "SubscriptionUpdateSubscriptionResponseBody";
  }
}

/** @internal */
export const SubscriptionUpdateSubscriptionSubscriptionsResponseBody$inboundSchema:
  z.ZodType<
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    error: z.string(),
  })
    .transform((v) => {
      return new SubscriptionUpdateSubscriptionSubscriptionsResponseBody(v);
    });

/** @internal */
export type SubscriptionUpdateSubscriptionSubscriptionsResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const SubscriptionUpdateSubscriptionSubscriptionsResponseBody$outboundSchema:
  z.ZodType<
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody$Outbound,
    z.ZodTypeDef,
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody
  > = z.instanceof(SubscriptionUpdateSubscriptionSubscriptionsResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      error: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriptionUpdateSubscriptionSubscriptionsResponseBody$ {
  /** @deprecated use `SubscriptionUpdateSubscriptionSubscriptionsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody$inboundSchema;
  /** @deprecated use `SubscriptionUpdateSubscriptionSubscriptionsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody$outboundSchema;
  /** @deprecated use `SubscriptionUpdateSubscriptionSubscriptionsResponseBody$Outbound` instead. */
  export type Outbound =
    SubscriptionUpdateSubscriptionSubscriptionsResponseBody$Outbound;
}

/** @internal */
export const SubscriptionUpdateSubscriptionResponseBody$inboundSchema:
  z.ZodType<SubscriptionUpdateSubscriptionResponseBody, z.ZodTypeDef, unknown> =
    z.object({
      message: z.string(),
      error: z.string(),
    })
      .transform((v) => {
        return new SubscriptionUpdateSubscriptionResponseBody(v);
      });

/** @internal */
export type SubscriptionUpdateSubscriptionResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const SubscriptionUpdateSubscriptionResponseBody$outboundSchema:
  z.ZodType<
    SubscriptionUpdateSubscriptionResponseBody$Outbound,
    z.ZodTypeDef,
    SubscriptionUpdateSubscriptionResponseBody
  > = z.instanceof(SubscriptionUpdateSubscriptionResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      error: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriptionUpdateSubscriptionResponseBody$ {
  /** @deprecated use `SubscriptionUpdateSubscriptionResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    SubscriptionUpdateSubscriptionResponseBody$inboundSchema;
  /** @deprecated use `SubscriptionUpdateSubscriptionResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    SubscriptionUpdateSubscriptionResponseBody$outboundSchema;
  /** @deprecated use `SubscriptionUpdateSubscriptionResponseBody$Outbound` instead. */
  export type Outbound = SubscriptionUpdateSubscriptionResponseBody$Outbound;
}
