/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * No Transaction was found with the given the Id
 */
export type TransactionsGetResponseBodyData = {
  message: string;
  error: string;
};

/**
 * No Transaction was found with the given the Id
 */
export class TransactionsGetResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: TransactionsGetResponseBodyData;

  constructor(err: TransactionsGetResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "TransactionsGetResponseBody";
  }
}

/** @internal */
export const TransactionsGetResponseBody$inboundSchema: z.ZodType<
  TransactionsGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new TransactionsGetResponseBody(v);
  });

/** @internal */
export type TransactionsGetResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const TransactionsGetResponseBody$outboundSchema: z.ZodType<
  TransactionsGetResponseBody$Outbound,
  z.ZodTypeDef,
  TransactionsGetResponseBody
> = z.instanceof(TransactionsGetResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionsGetResponseBody$ {
  /** @deprecated use `TransactionsGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = TransactionsGetResponseBody$inboundSchema;
  /** @deprecated use `TransactionsGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = TransactionsGetResponseBody$outboundSchema;
  /** @deprecated use `TransactionsGetResponseBody$Outbound` instead. */
  export type Outbound = TransactionsGetResponseBody$Outbound;
}
