/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { developerToolsCreatePaymentProviderKey } from "../../funcs/developerToolsCreatePaymentProviderKey.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiKeysPaymentProviderRequestBody$inboundSchema
    .optional(),
};

export const tool$developerToolsCreatePaymentProviderKey: ToolDefinition<
  typeof args
> = {
  name: "developer-tools-create-payment-provider-key",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await developerToolsCreatePaymentProviderKey(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
