/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesList } from "../../funcs/pricesList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$pricesList: ToolDefinition = {
  name: "prices-list",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await pricesList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
