/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersAddressesCreate } from "../funcs/customersAddressesCreate.js";
import { customersAddressesGet } from "../funcs/customersAddressesGet.js";
import { customersAddressesList } from "../funcs/customersAddressesList.js";
import { customersAddressesUpdate } from "../funcs/customersAddressesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Addresses extends ClientSDK {
  async list(
    request: operations.AddressesListRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.AddressesListResponseBody>> {
    return unwrapAsync(customersAddressesList(
      this,
      request,
      options,
    ));
  }

  async create(
    request: operations.AddressesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesCreateResponseBody> {
    return unwrapAsync(customersAddressesCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.AddressesGetRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesGetResponseBody> {
    return unwrapAsync(customersAddressesGet(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.AddressesUpdateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesUpdateResponseBody> {
    return unwrapAsync(customersAddressesUpdate(
      this,
      request,
      options,
    ));
  }
}
